server:
  port: 8081
spring:
  jmx:
    enabled: false   
  datasource:
    url: jdbc:mysql://localhost:3308/sport
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: never
  mail:
    host: smtp.gmail.com
    port: 587
    username: testemail@gmail.com
    password: fffffffff
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
